### ISSUE TITLE
README typos

### ISSUE THREAD

**Issue by MichalYoung** [neil-kulkarni/arvada#4]
Nicely packaged.  I ran into a couple of little issues trying to follow examples in the README, running on MacOS.   Both appear in the sample line 
```
python3 search.py external .bc-example/bc-wrapper.sh bc-example/test_set bc-example.log 100
```

The first is that `.bc-example` should probably be `./bc-example`.  The second is that the argument `100` does not seem to be recognized: 
```
michal$ python3 search.py external ./bc-example/bc-wrapper.sh bc-example/test_set bc-example.log 100
usage: search.py [-h] {internal,external} ...
search.py: error: unrecognized arguments: 100
```

I have only tested on MacOS, so I can't rule out that these are environment-specific issues, but they don't seem like the kind of thing that would differ from one *nix to another.

**Comment by carolemieux** [comment]
Ah, thanks for pointing this out! I refactored the argparse before release but didn't update the bc-example instructions accordingly. Definitely typos (:

I have updated the readme with the correct search command:

```$ python3 search.py external ./bc-example/bc-wrapper.sh bc-example/train_set bc-example.log```

and eval command:
```$ python3 eval.py external -n 100 ./bc-example/bc-wrapper.sh bc-example/test_set bc-example.log```

Both of these run on my MacOS machine, but let me know if there are any further issues and I will reopen!
